In [25]:
import numpy as np
import os
import pandas as pd
from arcpy import env
from arcpy import TableToTable_conversion

dirWork = os.getcwd()
dirData = os.path.join(dirWork, r'data')
dirResults = os.path.join(dirWork, r'results')

print("Working Directory: " + dirWork)
print("Data Directory: " + dirData)
print("Results Directory: " + dirResults)

#define variables

dbf_Forecasts = os.path.join(dirData, r'StatewideForecasts_withUSTM_20201208.dbf')
csv_Forecasts = os.path.join(dirResults, r'forecasts_withSummit.csv')
json_Forecasts = os.path.join(dirResults, r'forecasts_withSummit.json')

# Create function that converts dbfs to csvs using arcpy
def dbfToCSV(dbf, csv):
    TableToTable_conversion(dbf, os.path.dirname(csv), os.path.basename(csv))

# Allow arcpy to overwrite output files
env.overwriteOutput = True

# convert dbfs to csvs
dbfToCSV(dbf_Forecasts, csv_Forecasts)

Working Directory: E:\GitHub\Traffic-Volume-Forecasts
Data Directory: E:\GitHub\Traffic-Volume-Forecasts\data
Results Directory: E:\GitHub\Traffic-Volume-Forecasts\results

In [26]:
df_Forecasts = pd.read_csv(csv_Forecasts)
df_Forecasts

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,OID_,OBJECTID_1,RELEASE,SEGID,ROUTE_ID,BMP,EMP,FULLNAME,CO_FIPS,CO_NAME,...,FAC_SUM,FAC_FAL,FAC_MAXMO,FAC_MAX,FACMANADJ,SUTRUCKS,CUTRUCKS,SUBAREAID,SR_FAR,Publish
0,NaN,1,2019 RTP v8.3.1 20200508,0068_036.0,0068,36.037998,38.106998,CAMP WILLIAMS R,35,SALT LAKE,...,0.000,0.000,0.0,0.000,0.0,0.000,0.000,0,,0
1,NaN,2,2019 RTP v8.3.1 20200508,WFRC_8000,WFRC,1.488000,1.488000,,35,SALT LAKE,...,0.000,0.000,0.0,0.000,0.0,0.000,0.000,0,,0
2,NaN,3,2019 RTP v8.3.1 20200508,0131_001.7,0131,1.742000,3.047000,PORTER ROCKWELL,35,SALT LAKE,...,0.000,0.000,0.0,0.000,0.0,0.000,0.000,0,,0
3,NaN,4,2019 RTP v8.3.1 20200508,0068_038.1,0068,38.106998,39.167000,CAMP WILLIAMS R,35,SALT LAKE,...,0.000,0.000,0.0,0.000,0.0,0.000,0.000,0,,0
4,NaN,5,2019 RTP v8.3.1 20200508,2927_000.0,2927,0.000000,1.019000,DEER RIDGE DR,35,SALT LAKE,...,0.000,0.000,0.0,0.000,0.0,0.000,0.000,0,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8491,NaN,8492,,0084_112.1,84,112.071999,112.750000,I-84 EB FWY,43,SUMMIT,...,1.206,0.999,7.0,1.242,0.0,0.130,0.380,4,,0
8492,NaN,8493,,0150_014.6,150,14.604999,23.242001,HWY 150,43,SUMMIT,...,1.994,1.190,7.0,2.264,0.0,0.130,0.100,4,,0
8493,NaN,8494,,2610_023.0,2610,23.004000,23.502001,,43,SUMMIT,...,1.088,1.033,8.0,1.092,0.0,0.017,0.012,4,,0
8494,NaN,8495,,0150_024.7,150,23.242001,28.118000,HWY 150,43,SUMMIT,...,1.994,1.190,7.0,2.264,0.0,0.130,0.100,4,,0
8495,NaN,8496,,,0,0.000000,0.000000,,0,,...,0.000,0.000,0.0,0.000,0.0,0.000,0.000,0,,0

In [27]:
meltIndex    = ['SEGID']
valueColumns = ['AADT2017','F2019','F2024','F2030','F2040','F2050']
df_Forecasts_melt = pd.melt(df_Forecasts, id_vars=meltIndex, value_vars=valueColumns)
df_Forecasts_melt.columns = ('SEGID','FCOL','ForecastAADT')
df_Forecasts_melt['FYEAR'] = (df_Forecasts_melt['FCOL'].str[-4:]).astype('int64')
df_Forecasts_melt = df_Forecasts_melt[['SEGID','FYEAR','ForecastAADT']]
df_Forecasts_melt.columns = ('S','Y','F')
df_Forecasts_melt = df_Forecasts_melt.sort_values(by=['S'])
df_Forecasts_melt

               S     Y      F
25487             2024      0
42479             2040      0
33983             2030      0
16991             2019      0
8495              2017      0
...          ...   ...    ...
19775  WFRC_8219  2024      0
28271  WFRC_8219  2030   6200
36767  WFRC_8219  2040   6400
2783   WFRC_8219  2017      0
45263  WFRC_8219  2050  13500

[50976 rows x 3 columns]

In [28]:
df_Forecasts_melt.to_json(json_Forecasts,orient='records')